### PR TITLE
fix: decrypt password in firefox

### LINKED ISSUE #43: Doesn't extract passwords from Firefox
I am using both **release 0.2.8** and my build from latest source with this commands:

- .\hack-browser-data.exe -b all -f json -dir results -cc
- .\hack-browser-data.exe -b firefox -f json -dir results -cc
- .\hack-browser-data.exe -b all

It does find Everthing on Edge (version 86.0.622.69) and chrome (version 86.0.4240.198) but no luck in finding passwords from firefox.

**Desktop :**
 - OS Name : Windows 10 2004
 - Browser Name : FireFox
 - Browser Version : 78.0.1 and 82.0.3 (latest)

Additional context :
I have tried both running command in privileged mode and while firefox processes are terminated.
Also logs aren't clear and too much go error in case it doesn't find anything. For firefox and this command `.\hack-browser-data.exe -b all -f json -dir results -cc` logs look like this:
`decrypt_windows.go:122: error asn1: structure error: tags don't match (16 vs {class:0 tag:4 length:20 isCompound:false}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} SequenceC @2
parse.go:523: error decrypt meta data failed asn1: structure error: tags don't match (16 vs {class:0 tag:4 length:20 isCompound:false}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} SequenceC @2
cmd.go:77: error asn1: structure error: tags don't match (16 vs {class:0 tag:4 length:20 isCompound:false}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} SequenceC @2
[x]:  Get 0 passwords, filename is results/firefox_password.json
[x]:  Get 27 bookmarks, filename is results/firefox_bookmark.json
[x]:  Get 854 cookies, filename is results/firefox_cookie.json
[x]:  Get 21277 history, filename is results/firefox_history.json`

### PR DESCRIPTION
**Pull request by mirefly**
I only tested in Firefox 78.7.0esr (Debian 10), but this patch might also fix #43

### CODE REVIEW

**Comment by moonD4rk** [comment]
Thank you very much for submitting the PR, I will check if it is also the cause of decryption failure for other operating systems.

**Comment by dennyvsdev** [comment]
I have tried both mirefly and [2 Feb](https://github.com/moonD4rk/HackBrowserData/commit/83fc996a334124cb06d42b1248ed0e1a5202b1de) version of the original but still no luck.

```
decrypt_windows.go:122: error asn1: structure error: tags don't match (16 vs {class:0 tag:4 length:20 isCompound:false}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} SequenceC @2
parse.go:525: error decrypt meta data failed asn1: structure error: tags don't match (16 vs {class:0 tag:4 length:20 isCompound:false}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} SequenceC @2
cmd.go:92: error asn1: structure error: tags don't match (16 vs {class:0 tag:4 length:20 isCompound:false}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} SequenceC @2
```

**Comment by moonD4rk** [comment]
@dennyvsdev What's your firefox and OS version. The reason for the decryption failure is that this version of firefox has a different asn1 structure.

I will merge this PR tomorrow and try to fix the issue.

**Comment by dennyvsdev** [comment]
> 
> 
> @dennyvsdev What's your firefox and OS version. The reason for the decryption failure is that this version of firefox has a different asn1 structure.
> 
> I will merge this PR tomorrow and try to fix the issue.

Firefox 84.0.2
Windows 10.0.18363

**Comment by moonD4rk** [comment]
hi, 我认为我已经修复了 firefox 密码解密失败的问题，如果还是错误，可以提交 issues 
commit https://github.com/moonD4rk/HackBrowserData/commit/f8dc8bb418d75ad4d7e108f715254bdae2604eaf

**Comment by moonD4rk** [comment]
Hi, I think I've fixed the firefox password decryption failure issue, if it's still wrong, you can open an issue.

commit: https://github.com/moonD4rk/HackBrowserData/commit/f8dc8bb418d75ad4d7e108f715254bdae2604eaf

**Pull request merged**
